Traceback (most recent call last):
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\r.herron\Anaconda3\envs\fina-6333\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ind = (
    yf.download(tickers='^GSPC ^DJI ^IXIC ^FTSE ^N225 ^HSI', session=session)
    .rename_axis(columns=['Variable', 'Index'])
    .stack()
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_7872\4138742815.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m ind = (
[1;32m----> 2[1;33m     [0myf[0m[1;33m.[0m[0mdownload[0m[1;33m([0m[0mtickers[0m[1;33m=[0m[1;34m'^GSPC ^DJI ^IXIC ^FTSE ^N225 ^HSI'[0m[1;33m,[0m [0msession[0m[1;33m=[0m[0msession[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m     [1;33m.[0m[0mrename_axis[0m[1;33m([0m[0mcolumns[0m[1;33m=[0m[1;33m[[0m[1;34m'Variable'[0m[1;33m,[0m [1;34m'Index'[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [1;33m.[0m[0mstack[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m )

[1;31mTypeError[0m: download() got an unexpected keyword argument 'session'
TypeError: download() got an unexpected keyword argument 'session'

